### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by BoraSchninsky** [Madelena/hass-config-public#13]
Where can i have the pink theme ?

**Comment by Madelena** [comment]
It's at https://github.com/Madelena/Metrology-for-Hass 😀

**Comment by BoraSchninsky** [comment]
Thank you!! Gesendet von Mail für Windows Von: Madelena MakGesendet: Donnerstag, 23. Februar 2023 23:25An: Madelena/hass-config-publicCc: Bora Schninsky; AuthorBetreff: Re: [Madelena/hass-config-public] Theme (Issue #13) It's at https://github.com/Madelena/Metrology-for-Hass 😀—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
