### ISSUE TITLE
Template: bar_row

### ISSUE THREAD

**Issue by milandzuris** [Madelena/hass-config-public#27]
Hi, where i find template: bar_row?, thx

          - type: entities
            style: *style-maintenance-entities
            entities:
              - entity: sensor.astralplane_hue_sensor_battery
                type: custom:button-card
                template: bar_row
                name: Astralplane
                label: 2×AA
                show_label: true

**Comment by Dae657** [comment]
it's in hass-config-public/ui/templates/button-card/rows.yaml. See [here](https://github.com/Madelena/hass-config-public/blob/main/ui/templates/button-card/rows.yaml)
