### ISSUE TITLE
psychrometric humidity translations

### ISSUE THREAD

**Issue by vekexasia** [Madelena/hass-config-public#4]
Hello there.

First of all great work. I was trying to use your psychrometric illustration to plot my stuff.

This is the code you use when performing the style transformation for each idnicator

`                style: |
                  >
                  var x = (parseFloat(entity.state) + 20) / 65 * 1007 - 11;
                  var y = 665 - (parseFloat(states['sensor.lumi_lumi_weather_humidity_ufficio'].state) / 35 * 665) - 155; 
                  return `transform: translate(${x}px, ${y}px);`;`

The `x` translation seems to work just fine but `y` provides me negative values. I suspect you have some kind of absolute humidity computation that gives the value to make the formula works. 

Can you share the computation formula or point me to the right direction?

**Comment by Madelena** [comment]
I use the Thermal Comfort integration for calculating absolute humidity, so the formula you quoted is mostly used for figuring out the coordinates of where to put the indicator.

**Comment by vekexasia** [comment]
I totally missed the integration. THANKS
